/*

    IMPORTANT! This file is auto-generated by the Jucer each time you save your
    project - if you alter its contents, your changes may be overwritten!

    This is the header file that your files should include in order to get all the
    Juce library headers. You should NOT include juce.h or juce_amalgamated.h directly in
    your own source files, because that wouldn't pick up the correct Juce configuration
    options for your app.

*/

#ifndef __APPHEADERFILE_9C46E6CC__
#define __APPHEADERFILE_9C46E6CC__

#include "AppConfig.h"
#include "JucePluginCharacteristics.h"

#include "modules/juce_core/juce_core.h"
#include "modules/juce_audio_basics/juce_audio_basics.h"
#include "modules/juce_audio_devices/juce_audio_devices.h"
#include "modules/juce_audio_formats/juce_audio_formats.h"
#include "modules/juce_audio_processors/juce_audio_processors.h"
#include "modules/juce_audio_utils/juce_audio_utils.h"
#include "modules/juce_data_structures/juce_data_structures.h"
#include "modules/juce_events/juce_events.h"
#include "modules/juce_graphics/juce_graphics.h"
#include "modules/juce_gui_basics/juce_gui_basics.h"
#include "modules/juce_gui_extra/juce_gui_extra.h"

using namespace juce;

#endif   // __APPHEADERFILE_9C46E6CC__
