/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_D899ED8A__
#define __PLUGINEDITOR_H_D899ED8A__

#include "juce.h"
#include "JucePluginCharacteristics.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class DistrhoPluginAudioProcessorEditor  : public AudioProcessorEditor,
                                           public SliderListener,
                                           public Timer
{
public:
    DistrhoPluginAudioProcessorEditor (DistrhoPluginAudioProcessor* ownerFilter);
    ~DistrhoPluginAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics& g);
    void resized();
    
    //==============================================================================
    void sliderValueChanged (Slider* slider);

    //==============================================================================
    void timerCallback();
    
private:
//     Slider sLow, sMid, sHigh, sMaster;
//     Slider sLowMidFreq, sMidHighFreq;

    Image backgroundImage;

    DistrhoPluginAudioProcessor* getProcessor() const
    {
        return static_cast <DistrhoPluginAudioProcessor*> (getAudioProcessor());
    }
};


#endif  // __PLUGINEDITOR_H_D899ED8A__
