/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_D899ED8A__
#define __PLUGINEDITOR_H_D899ED8A__

#include "juce.h"
#include "JucePluginCharacteristics.h"
#include "PluginProcessor.h"

#include "../../common/FilmStripKnob.h"
#include "../../common/ImageSlider.h"


//==============================================================================
/**
*/
class DistrhoPluginAudioProcessorEditor  : public AudioProcessorEditor,
                                           public SliderListener,
                                           public Timer
{
public:
    DistrhoPluginAudioProcessorEditor (DistrhoPluginAudioProcessor* ownerFilter);
    ~DistrhoPluginAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics& g);
    void sliderValueChanged (Slider* caller);

    //==============================================================================
    void timerCallback();

private:
    ImageSlider* sLow;
    ImageSlider* sMid;
    ImageSlider* sHigh;
    ImageSlider* sMaster;
    FilmStripKnob* sLowMidFreq;
    FilmStripKnob* sMidHighFreq;

    Image knobImage;
    Image sliderImage;
    Image backgroundImage;

    DistrhoPluginAudioProcessor* getProcessor() const
    {
        return static_cast <DistrhoPluginAudioProcessor*> (getAudioProcessor());
    }
};


#endif  // __PLUGINEDITOR_H_D899ED8A__
