# Compile all the pizmidi plugins

all: build


build:
	$(MAKE) -C midi2qwerty16
	$(MAKE) -C midi16CCRouter
	$(MAKE) -C midiAlias
	$(MAKE) -C midiAudioToCC
	$(MAKE) -C midiBlackKeyFilter
	$(MAKE) -C midiCCModulator
	$(MAKE) -C midiCCReset
	$(MAKE) -C midiCCStepper
	$(MAKE) -C midiCCToggle
	$(MAKE) -C midiChannelFilter
	$(MAKE) -C midiChannelize
	$(MAKE) -C midiChordHold
	$(MAKE) -C midiChordSplit
	$(MAKE) -C midiChs_noGUI
	$(MAKE) -C midiConverter3
	$(MAKE) -C midiDelay
	$(MAKE) -C midiDuplicateBlocker
	$(MAKE) -C midiExactDelay
	$(MAKE) -C midiFingered
	$(MAKE) -C midiForceToKey
	$(MAKE) -C midiForceToRange
	$(MAKE) -C midiInvertNotes
	$(MAKE) -C midiKeySplit
	$(MAKE) -C midiKeySplit4
	$(MAKE) -C midiNotchFilter
	$(MAKE) -C midiNoteGroups
	$(MAKE) -C midiNotesToCC
	$(MAKE) -C midiNoteToggle
	$(MAKE) -C midiNRPNConverter
	$(MAKE) -C midiOverlappingNoteKiller
	$(MAKE) -C midiPitchBendQuantize
	$(MAKE) -C midiPolyphony
	$(MAKE) -C midiProbability
	$(MAKE) -C midiProgramChange
	$(MAKE) -C midiScaleChanger
	$(MAKE) -C midiSimpleLFO
	$(MAKE) -C midiSostenuto
	$(MAKE) -C midiStrum
	$(MAKE) -C midiStuckNoteKiller
	$(MAKE) -C midiSwing
	$(MAKE) -C midiTranspose
	$(MAKE) -C midiTriggerList
	$(MAKE) -C midiVelocityScale


clean:
	$(MAKE) clean -C midi2qwerty16
	$(MAKE) clean -C midi16CCRouter
	$(MAKE) clean -C midiAlias
	$(MAKE) clean -C midiAudioToCC
	$(MAKE) clean -C midiBlackKeyFilter
	$(MAKE) clean -C midiCCModulator
	$(MAKE) clean -C midiCCReset
	$(MAKE) clean -C midiCCStepper
	$(MAKE) clean -C midiCCToggle
	$(MAKE) clean -C midiChannelFilter
	$(MAKE) clean -C midiChannelize
	$(MAKE) clean -C midiChordHold
	$(MAKE) clean -C midiChordSplit
	$(MAKE) clean -C midiChs_noGUI
	$(MAKE) clean -C midiConverter3
	$(MAKE) clean -C midiDelay
	$(MAKE) clean -C midiDuplicateBlocker
	$(MAKE) clean -C midiExactDelay
	$(MAKE) clean -C midiFingered
	$(MAKE) clean -C midiForceToKey
	$(MAKE) clean -C midiForceToRange
	$(MAKE) clean -C midiInvertNotes
	$(MAKE) clean -C midiKeySplit
	$(MAKE) clean -C midiKeySplit4
	$(MAKE) clean -C midiNotchFilter
	$(MAKE) clean -C midiNoteGroups
	$(MAKE) clean -C midiNotesToCC
	$(MAKE) clean -C midiNoteToggle
	$(MAKE) clean -C midiNRPNConverter
	$(MAKE) clean -C midiOverlappingNoteKiller
	$(MAKE) clean -C midiPitchBendQuantize
	$(MAKE) clean -C midiPolyphony
	$(MAKE) clean -C midiProbability
	$(MAKE) clean -C midiProgramChange
	$(MAKE) clean -C midiScaleChanger
	$(MAKE) clean -C midiSimpleLFO
	$(MAKE) clean -C midiSostenuto
	$(MAKE) clean -C midiStrum
	$(MAKE) clean -C midiStuckNoteKiller
	$(MAKE) clean -C midiSwing
	$(MAKE) clean -C midiTranspose
	$(MAKE) clean -C midiTriggerList
	$(MAKE) clean -C midiVelocityScale
