/*
 * DISTRHO Plugin Information
 */

#define DISTRHO_PLUGIN_URI "urn:distrho:Bitcrusher"

#define DISTRHO_PLUGIN_BASE_VST        1
#define DISTRHO_PLUGIN_BASE_VST_COMPAT 1

#define DISTRHO_PLUGIN_IS_SYNTH 0

#define DISTRHO_PLUGIN_NUM_INPUTS  2
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2

#define DISTRHO_PLUGIN_WANTS_MIDI_INPUT  0
#define DISTRHO_PLUGIN_WANTS_MIDI_OUTPUT 0
#define DISTRHO_PLUGIN_WANTS_PRESETS     0
#define DISTRHO_PLUGIN_WANTS_UI          0
